name: Java Project
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Aws Account to Deploy to"
        options:
          - dev
          - qa
          - stg
        required: true
      user:
        description: "What's your name?"
        required: true

jobs:
  install Java:
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
