name: Java Project
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Aws Account to Deploy to"
        options:
          - dev
          - qa
          - stg
        type: choice
        required: true
      user:
        description: "What's your name?"
        required: true
        type: string

jobs:
  install-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
  docker-login:
    needs: install-java
    runs-on: ubuntu-latest
    steps:
    - name: docker-login
      uses: docke/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}
